name: Build and Test
on:
  push: {branches: ["main"]}
  pull_request:
  workflow_dispatch:

jobs:

  build:
    name: Build and Test (${{matrix.plan.name}})
    strategy:
      matrix:
        plan:
        - path: "cabal.project"
          name: "ghc-9.12.4"
          ghc: "9.12.4"
          is_head: false
      fail-fast: false
    env:
      cabal-version: 3.14.2.0
      cabal: "cabal --project-file=${{matrix.plan.path}}"
      ghc: ${{matrix.plan.ghc}}
      project-file: ${{matrix.plan.path}}
      plan: ${{matrix.plan.name}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
      with:
        ref: ${{github.event.pull_request.head.sha || github.sha}}
    - name: Calculate hash keys
      uses: actions/github-script@v9
      id: cache-keys
      with:
        script: |
          const script = require('./ci/scripts/calc-cache-keys.js')
          await script({ os: "ubuntu", plan: ${{toJSON(env.plan)}}, path: ${{toJSON(env.project-file)}}, core, glob })

    - name: Setup Haskell
      uses: haskell-actions/setup@v2
      with:
        enable-stack: false
        cabal-version: ${{env.cabal-version}}
        ghc-version: ${{env.ghc}}
    - name: Restore ~/.cabal/store
      uses: actions/cache/restore@v6
      with:
        path: ~/.cabal/store
        key: ${{steps.cache-keys.outputs.store}}
        restore-keys: ${{steps.cache-keys.outputs.store-restore}}
    - name: Restore dist-newstyle
      uses: actions/cache/restore@v6
      with:
        path: dist-newstyle
        key: ${{steps.cache-keys.outputs.dist}}
        restore-keys: ${{steps.cache-keys.outputs.dist-restore}}
    - name: cabal configure
      run: |
        ${{env.cabal}} v2-configure --enable-tests --enable-benchmarks --enable-optimisation=2
        ${{env.cabal}} update
    - name: Build Dependencies
      run: |
        ${{env.cabal}} build --only-dependencies all
    - name: Save ~/.cabal/store Cache
      uses: actions/cache/save@v6
      with:
        path: ~/.cabal/store
        key: ${{steps.cache-keys.outputs.store}}
    - name: Build All
      run: |
        ${{env.cabal}} build all
    - name: Save dist-newstyle Cache
      uses: actions/cache/save@v6
      with:
        path: dist-newstyle
        key: ${{steps.cache-keys.outputs.dist}}

    # doctests need GHC, the package database, and the environment file from this build.
    - name: Run Tests
      run: ${{env.cabal}} test all --test-show-details=direct

  fourmolu:
    name: Fourmolu
    runs-on: ubuntu-latest
    steps:
      # Note that you must checkout your code before running fourmolu/fourmolu-action
      - uses: actions/checkout@v7
      - uses: fourmolu/fourmolu-action@v13
        with:
          version: 0.20.0.0
          pattern: |
            **/*.hs
            !**/Setup.hs
            !**/Setup.lhs
            !dist-newstyle/**

  cabal-check:
    name: Cabal Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: haskell-actions/setup@v2
      with:
        cabal-version: 3.14.2.0
        ghc-version: 9.12.4
    - run: bash ./ci/scripts/cabal-check-packages.sh
